#!/bin/sh /etc/rc.common

START=99

start()
{

  remote_ip=$(uci get dnsmasq_route.config.remote_ip)
  dns_server=$(uci get dnsmasq_route.config.dns_server)
  localnet_only=$(uci get dnsmasq_route.config.localnet_only)
  table=$(uci get dnsmasq_route.config.table) #路由表编号

  if [ "a$localnet_only" == "a1" ] ; then
    sip=$(uci get network.lan.ipaddr)
    netmask=$(uci get network.lan.netmask)
    from_localnet_only="-s $sip/$netmask"
  fi

  if [ "a$table" == "a" ] ; then
    table=107
  fi

  if ! [ -e /etc/dnsmasq_route.ini ] ; then
    echo github.com > /etc/dnsmasq_route.ini
  fi
  echo "#auto gen from /etc/dnsmasq_route.ini" > /tmp/dnsmasq.d/dnsmasq_ipset.conf
  cat /etc/dnsmasq_route.ini |grep -v  -e ^# -e ^$ |\
  while read hostname note
  do
    echo "server=/$hostname/$dns_server" >> /tmp/dnsmasq.d/dnsmasq_ipset.conf
    echo "ipset=/$hostname/gfw_list" >> /tmp/dnsmasq.d/dnsmasq_ipset.conf
  done
  /etc/init.d/dnsmasq restart
  echo "dnsmasq_route has started."
}

stop(){
   #清理分流路由
   rm /tmp/dnsmasq.d/dnsmasq_ipset.conf
   ip ru list |grep ^290 |while read prefix from sip to dip lookup
   do
    ip rule del from $sip to $dip
  done
  echo "dnsmasq_route has stopped."
  /etc/init.d/dnsmasq restart
}

restart(){
       start
}

