#!/bin/sh /etc/rc.common

START=99

remote_ip=$(uci get dnsmasq_route.config.remote_ip)
dns_server=$(uci get dnsmasq_route.config.dns_server)

start(){
	#table
        if ! [ -e /etc/dnsmasq_route.ini ] ; then
        	echo github.com > /etc/dnsmasq_route.ini
	fi
        echo "#auto gen from /etc/dnsmasq_route.ini" > /tmp/dnsmasq.d/dnsmasq_route.conf
        cat /etc/dnsmasq_route.ini |grep -v  -e ^# -e ^$ |\
        while read hostname note
        do
        	echo "server=/$hostname/$dns_server" >> /tmp/dnsmasq.d/dnsmasq_route.conf
        done
        /etc/init.d/dnsmasq restart
        if [ "`grep '^107' /etc/iproute2/rt_tables`" ] ; then
        	table=106
        else
        	table=107
	fi
	if ! [ "`ip route list default table $table |grep $remote_ip`" ] ; then
		ip route add default via $remote_ip table $table
	fi
        if [ "`ps |grep dnsmasq_route |grep -v -e dnsmasq_route.sh -e grep -e init.d`" ] ;then
		echo "dnsmasq_route has already started."
        else
		nohup dnsmasq_route.sh $dns_server $remote_ip $table >/dev/null 2>/dev/null &
		echo "dnsmasq_route has started."
	fi
}

stop(){
	kill $( ps |grep  -e "dnsmasq_route -d" -e dnsmasq_route.sh -e 128129 |awk '{printf " " $1}' )
	echo "dnsmasq_route has stopped."
}

restart(){
	stop
	sleep 1
	start
	echo "dnsmasq_route has restarted."
}
